[package]
name = "openstrike-mods"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
openstrike-character = { path = "../openstrike-character" }
openstrike-core = { path = "../openstrike-core", default-features = false, features = ["libm"] }
glam = { version = "0.33", default-features = false, features = ["libm"] }

[build-dependencies]
glam = { version = "0.33", default-features = false, features = ["libm"] }
serde_json = "1"
